services:
  mongodb-container:
    image: ecommerce-mongodb:latest
    build:
      context: /mongodb
      dockerfile: /Dockerfile
    ports:
      - "27017:27017"

  mysql-container:
    image: ecommerce-mysql:latest
    build:
      context: /mysql
      dockerfile: /Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"

  postgres-container:
    image: ecommerce-postgres:latest
    build:
      context: /postgres
      dockerfile: /Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=eCommerceUsers
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"

  apigateway:
    image: apigateway:latest
    build:
      context: ./Orders/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - orders-microservice
      - products-microservice
      - users-microservice

  products-microservice:
    image: products-microservice:latest
    build:
      context: ./Products
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql-host-productsmicroservice
      - MYSQL_PASSWORD=admin
      - RABBITMQ_Hostname=rabbitmq
      - RABBITMQ_Username=user
      - RABBITMQ_Password=password
      - RABBITMQ_Port=5672
      - RABBITMQ_Products_Exchange=product.exchange
    hostname: products-microservice

  users-microservice:
    image: users-microservice:latest
    build:
      context: ./Users
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres-container
    hostname: users-microservice

  orders-microservice:
    image: orders-microservice:latest
    build:
      context: ./Orders
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_HOST=mongodb-container
      - MONGO_PORT=27017
      - MONGO_DATABASE=OrdersDatabase
      - UsersMicroserviceName=apigateway
      - UsersMicroservicePort=5050
      - ProductsMicroserviceName=apigateway
      - ProductsMicroservicePort=5050
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_Hostname=rabbitmq
      - RABBITMQ_Username=user
      - RABBITMQ_Password=password
      - RABBITMQ_Port=5672
      - RABBITMQ_Products_Exchange=product.exchange
    depends_on:
      - mongodb-container
      - users-microservice
      - products-microservice
