apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: users-microservice
  ports:
    - 
      port: 9090
      targetPort: 9090
  type: ClusterIP
